# Generated by Django 4.1.7 on 2023-11-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_members',
            name='occupation',
            field=models.CharField(max_length=1000),
        ),
    ]
