# Generated by Django 4.1.6 on 2023-02-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(choices=[('KE', 'KENYAN'), ('FG', 'FOREIGNER')], max_length=2)),
                ('national_id', models.IntegerField(default=0, unique=True)),
                ('alien_id', models.IntegerField(default=0, unique=True)),
                ('passport_number', models.CharField(max_length=9, unique=True)),
                ('account_type', models.CharField(choices=[('INDI', 'Individual'), ('PSHIP', 'Partnership'), ('CO', 'Company')], max_length=5)),
                ('residency', models.CharField(choices=[('RE', 'Resident'), ('NRE', 'Non-Resident')], max_length=3)),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('date_of_incorporation', models.DateField()),
                ('date_of_registration', models.DateField()),
                ('account_number', models.IntegerField(default=0)),
            ],
        ),
    ]
