# Generated by Django 4.1.6 on 2023-02-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_bankingSolution', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountopening',
            name='alien_id',
        ),
        migrations.RemoveField(
            model_name='accountopening',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='accountopening',
            name='passport_number',
        ),
        migrations.AddField(
            model_name='accountopening',
            name='identification_doc',
            field=models.CharField(choices=[('ID', 'Kenyan Id'), ('AL', 'Kenyan Alien Id'), ('PPT', 'Passport')], default='ID', max_length=3),
        ),
        migrations.AddField(
            model_name='accountopening',
            name='identity_number',
            field=models.CharField(default=123456789, max_length=10, unique=True),
        ),
    ]
