# Generated by Django 4.1.6 on 2023-02-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_bankingSolution', '0002_remove_accountopening_alien_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountopening',
            name='date_of_incorporation',
        ),
        migrations.RemoveField(
            model_name='accountopening',
            name='date_of_registration',
        ),
        migrations.AddField(
            model_name='accountopening',
            name='company_business_name',
            field=models.CharField(max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='accountopening',
            name='date_of_birth',
            field=models.DateField(choices=[('d_o_b', 'Date of Birth'), ('d_o_i', 'Date of Incorporation'), ('d_o_r', 'Date of Registration')], max_length=5),
        ),
        migrations.AlterField(
            model_name='accountopening',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accountopening',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accountopening',
            name='second_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
