# Generated by Django 4.1.6 on 2023-02-06 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_bankingSolution', '0003_remove_accountopening_date_of_incorporation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountopening',
            name='birth_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='accountopening',
            name='date_of_birth',
            field=models.CharField(choices=[('d_o_b', 'Date of Birth'), ('d_o_i', 'Date of Incorporation'), ('d_o_r', 'Date of Registration')], max_length=5),
        ),
    ]
