# Generated by Django 4.1.6 on 2023-02-08 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_bankingSolution', '0004_accountopening_birth_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=6)),
                ('confirm_password', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='accountopening',
            name='company_business_name',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='accountopening',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accountopening',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accountopening',
            name='second_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
