# Generated by Django 4.1.6 on 2023-02-10 15:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App_bankingSolution', '0005_userregister_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountopening',
            name='opening_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
